CC = clang++
SRC_FILES = main.cpp LinkedList.cpp LinkedListNode.cpp
OBJ_NAME = test


# If pkg-config is available, prefer its flags (libs come after sources in link)
all:
	$(CC) -o $(OBJ_NAME) $(SRC_FILES)